Searchable encryption demo
cossacklabs/acra-engineering-demo pull request #53
Opened 2022-06-15 11:23 UTC by G1gg1L3s

This PR adds searchable encryption demo. It's a quintessence of the `python` and `python-mysql` because it supports two databases at once.

This PR should be review together with the corresponding [PR](https://github.com/cossacklabs/acra/pull/548) in the main Acra repo. Though I'm not sure how to run it from `run.sh`. Maybe use `COSSACKLABS_ACRA_VCS_BRANCH` or something.

The only difference from other demos is that the postgres uses `test` as an admin user, instead of `postgresql`. This is just to simplify the invokations of the client app, so there is no need to specify separate `--user` flag for the postgres case.

The Acra is configure with the `postgres` by default, but the readme suggests to change that, if the user wants to try the mysql.

2022-06-15 19:52 UTC, vixentael requested changes
👍

2022-06-15 19:52 UTC, vixentael commented on README.md
> +| 10  | [Search in encrypted data](#example-10-search-in-encrypted-data)                                                                          | Python client application, transparent encryption a
pls update this once #52 is merged, it will affect the numeration

2022-06-15 19:52 UTC, vixentael commented on README.md
> +### 2.6 Other resources to loot at
```suggestion
### 2.6 Other resources to look at 
```

2022-06-15 22:52 UTC, Lagovas commented on python-searchable/docker-compose.python-searchable.yml
> +        # We use internal 'server-postgresql' network for AcraServer and
lets update comment here and mention proper networks)

2022-06-15 22:52 UTC, Lagovas commented on python-searchable/docker-compose.python-searchable.yml
> +        # We use internal 'python-mysql' network for Django and
here is no django so lets remove or comment properly)

2022-06-15 22:52 UTC, Lagovas commented on python-searchable/docker-compose.python-searchable.yml
> +        # with an additional configuration in accordance with djangoproject
lets remove this comment. there is no djangoproject. maybe leave mention that it is official postgresql with some additions (ssl certs?)

2022-06-16 20:31 UTC, Lagovas approved these changes

2022-06-20 14:22 UTC, merged